Debugging

diff --git a/.github/workflows/project-style.yml b/.github/workflows/project-style.yml
--- a/.github/workflows/project-style.yml
+++ b/.github/workflows/project-style.yml
@@ -61,7 +61,19 @@ jobs:
           script: |
             const script = require('./workflows/.github/scripts/run-exec.js');
             return await script({exec, core});
-      
+
+      - name: 'Check extra main methods'
+        working-directory: '${{ env.USER_PATH }}/src/main/java'
+        run: |
+          RUN_STATUS=0
+          grep -rnoE --exclude=Driver.java '\s*public\s+static\s+void\s+main\s*\(' || RUN_STATUS=$?
+          if [[ RUN_STATUS -ne 1 ]]; then
+            echo "::error ::Except for Driver.java, you should delete old main methods from your code."
+            exit 1
+          fi
+          echo "Found 0 main methods."
+
+
       - name: 'Save step status'
         id: step_status
         uses: actions/github-script@v6
