Nesting workflows

diff --git a/.github/workflows/project-release.yml b/.github/workflows/project-release.yml
--- a/.github/workflows/project-release.yml
+++ b/.github/workflows/project-release.yml
@@ -76,52 +76,53 @@ jobs:
     runs-on: ubuntu-latest
     needs: ['parse_version']
     timeout-minutes: 1
+    uses: usf-cs272-fall2022/action-workflows/.github/workflows/project-compile.yml@main
 
-    steps:
-      - name: 'Checkout workflows'
-        id: checkout-workflows
-        uses: actions/checkout@v3
-        with:
-          repository: usf-cs272-fall2022/action-workflows
-          path: 'workflows'
+    # steps:
+    #   - name: 'Checkout workflows'
+    #     id: checkout-workflows
+    #     uses: actions/checkout@v3
+    #     with:
+    #       repository: usf-cs272-fall2022/action-workflows
+    #       path: 'workflows'
 
-      - name: 'Setup project code'
-        uses: ./workflows/.github/actions/project-setup
-        with:
-          user_repo:  '${{ github.repository }}'
-          test_repo:  '${{ github.repository_owner }}/${{ env.TEST_PATH }}'
-          user_cache: '${{ needs.parse_version.outputs.user_cache }}'
-          test_cache: '${{ needs.parse_version.outputs.test_cache }}'
+    #   - name: 'Setup project code'
+    #     uses: ./workflows/.github/actions/project-setup
+    #     with:
+    #       user_repo:  '${{ github.repository }}'
+    #       test_repo:  '${{ github.repository_owner }}/${{ env.TEST_PATH }}'
+    #       user_cache: '${{ needs.parse_version.outputs.user_cache }}'
+    #       test_cache: '${{ needs.parse_version.outputs.test_cache }}'
 
-      - name: 'Compile project code' 
-        working-directory: '${{ env.USER_PATH }}'
-        run: |
-          RUN_STATUS=0
-          mvn -ntp -DcompileOptionXlint=-Xlint:none -DcompileOptionXdoclint=-Xdoclint:none -Dmaven.compiler.showWarnings=false -DcompileOptionFail=false compile || RUN_STATUS=$?
-          if [[ RUN_STATUS -ne 0 ]]; then
-            echo "::error ::Unable to compile your project source code."
-            exit 1
-          fi
+    #   - name: 'Compile project code' 
+    #     working-directory: '${{ env.USER_PATH }}'
+    #     run: |
+    #       RUN_STATUS=0
+    #       mvn -ntp -DcompileOptionXlint=-Xlint:none -DcompileOptionXdoclint=-Xdoclint:none -Dmaven.compiler.showWarnings=false -DcompileOptionFail=false compile || RUN_STATUS=$?
+    #       if [[ RUN_STATUS -ne 0 ]]; then
+    #         echo "::error ::Unable to compile your project source code."
+    #         exit 1
+    #       fi
 
-      - name: 'Listing source code'
-        working-directory: '${{ env.USER_PATH }}'
-        run: |
-          ls -ACGR target/classes
+    #   - name: 'Listing source code'
+    #     working-directory: '${{ env.USER_PATH }}'
+    #     run: |
+    #       ls -ACGR target/classes
 
-      - name: 'Compile test code' 
-        working-directory: '${{ env.USER_PATH }}'
-        run: |
-          RUN_STATUS=0
-          mvn -ntp -DcompileOptionXlint=-Xlint:none -DcompileOptionXdoclint=-Xdoclint:none -Dmaven.compiler.showWarnings=false -DcompileOptionFail=false test-compile || RUN_STATUS=$?
-          if [[ RUN_STATUS -ne 0 ]]; then
-            echo "::error ::Unable to compile the project test code."
-            exit 1
-          fi
+    #   - name: 'Compile test code' 
+    #     working-directory: '${{ env.USER_PATH }}'
+    #     run: |
+    #       RUN_STATUS=0
+    #       mvn -ntp -DcompileOptionXlint=-Xlint:none -DcompileOptionXdoclint=-Xdoclint:none -Dmaven.compiler.showWarnings=false -DcompileOptionFail=false test-compile || RUN_STATUS=$?
+    #       if [[ RUN_STATUS -ne 0 ]]; then
+    #         echo "::error ::Unable to compile the project test code."
+    #         exit 1
+    #       fi
 
-      - name: 'Listing test code'
-        working-directory: '${{ env.USER_PATH }}'
-        run: |
-          ls -ACGR target/test-classes
+    #   - name: 'Listing test code'
+    #     working-directory: '${{ env.USER_PATH }}'
+    #     run: |
+    #       ls -ACGR target/test-classes
 
   check_tests:
     name: 'Check Current Tests'
